"""Python bindings for the SelectSpeak-owned native bridge."""

from .abi import (
    ActivationCallback,
    AudioEventCallback,
    AudioRequestHandle,
    CaptureCallback,
    NativeAudioBoundary,
    NativeAudioEvent,
    NativeAudioEventKind,
    NativeAudioFormat,
    NativeAudioSubmitResult,
    NativeCallError,
    NativeNaturalSynthesisResult,
    NativeSampleFormat,
    NativeStatus,
    NativeTerminalStatus,
    OcrCallback,
    VoiceAudioCallback,
    VoiceListCallback,
    VoiceWordCallback,
    check_native_status,
)
from .bindings import (
    NATIVE_API_VERSION,
    NativeBridge,
    NativeBridgeError,
    find_native_dll,
    get_native_bridge,
    shutdown_native_bridge,
)

__all__ = [
    "ActivationCallback",
    "AudioEventCallback",
    "AudioRequestHandle",
    "CaptureCallback",
    "NATIVE_API_VERSION",
    "NativeCallError",
    "NativeAudioBoundary",
    "NativeAudioEvent",
    "NativeAudioEventKind",
    "NativeAudioFormat",
    "NativeAudioSubmitResult",
    "NativeBridge",
    "NativeBridgeError",
    "NativeNaturalSynthesisResult",
    "NativeSampleFormat",
    "NativeStatus",
    "NativeTerminalStatus",
    "OcrCallback",
    "VoiceAudioCallback",
    "VoiceListCallback",
    "VoiceWordCallback",
    "check_native_status",
    "find_native_dll",
    "get_native_bridge",
    "shutdown_native_bridge",
]
